- name: mysql server
  hosts: mysql
  become: yes
  vars:
    sql_root_password: ExpenseApp@1

    
  tasks:
  - name: Install MySQL libraries
    ansible.builtin.pip:
      name: "{{ item }}"
      executable: pip3.9
    loop:
    - cryptography
    - PyMySQL


  - name: installing mysql
    ansible.builtin.package:
      name: mysql-server
      state: present

  - name: starting mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: true

  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: "{{ mysql_root_password }}""
      login_host: mysql.vengalareddy.site
    register: mysql_info
    ignore_errors: true

  - name: print out put
    ansible.builtin.debug:
      msg: "mysql info: {{ mysql_info }}"    

  - name: set root login_password
    ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ mysql_root_password }}" 
    when: mysql_info.failed is true    
